Repository home-assistant/hassbian-scripts, pull requests merged in 2018-10, with the labels that each got.

#189 Homeassistant: Add --force to initial install command.
  package/etc/systemd/system/install_homeassistant.service
Labels: cla-signed

#188 DuckDNS: Add remove function.
  docs/duckdns.md
  package/opt/hassbian/suites/duckdns.sh
Labels: cla-signed

#187 Homeassistant: Fixes revert issue.
  package/opt/hassbian/suites/homeassistant.sh
Labels: cla-signed

#186 Repo: Add release-drafter configuration.
  .github/release-drafter.yml
Labels: cla-signed

#185 Documentation cleanup
  README.md
  docs/appdaemon.md
  docs/cloud9.md
  docs/duckdns.md
  docs/hassbian.md
  docs/hassbian_config.md
  docs/homeassistant.md
  docs/hue.md
  docs/libcec.md
  docs/mariadb.md
  docs/mosquitto.md
  docs/mssql.md
  docs/postgresql.md
  docs/python.md
  docs/razberry.md
  docs/samba.md
  docs/tradfri.md
  docs/webterminal.md
Labels: cla-signed

#190 docs: Fixes tables for hassbian-config
  docs/hassbian_config.md
Labels: cla-signed

#191 DuckDns: fix typo in duckdns-install-package
  package/opt/hassbian/suites/duckdns.sh
Labels: Hacktoberfest, cla-signed, enhancement, script: duckdns

#192 Fix multiple typos in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: cla-signed

#193 DuckDns docs: add https hint and fix typo
  docs/duckdns.md
Labels: Hacktoberfest, cla-signed, enhancement

#197 homebridge: Add removal script.
  README.md
  docs/homebridge.md
  package/opt/hassbian/suites/homebridge.sh
Labels: Hacktoberfest, cla-signed, script: homebridge

#198 Update webterminal.md
  docs/webterminal.md
Labels: Hacktoberfest, cla-signed

#199 Update postgresql.md
  docs/postgresql.md
Labels: Hacktoberfest, cla-signed

#200 Update mariadb.md
  docs/mariadb.md
Labels: cla-signed

#195 Add install script for the Bluetooth monitor script
  README.md
  docs/monitor.md
  package/opt/hassbian/suites/monitor.sh
Labels: Hacktoberfest, New install script, cla-signed

#201 Add MOTD to the Hassbian image
  package/DEBIAN/control
  package/etc/update-motd.d/10-display-hostname
  package/etc/update-motd.d/20-sysinfo
  package/etc/update-motd.d/30-services
Labels: Hacktoberfest, cla-signed

#203 hassbian-config: Adds function to test PR's
  package/etc/bash_completion.d/hassbian-config
  package/usr/local/bin/hassbian-config
Labels: cla-signed

#205 hassbian-config: adds check-permission to developer-test-pr function
  package/usr/local/bin/hassbian-config
Labels: cla-signed

#204 Pihole
  README.md
  docs/pihole.md
  package/opt/hassbian/suites/pihole.sh
Labels: Hacktoberfest, New install script, cla-signed

#202 Bump dev version to 0.10.0
  package/DEBIAN/control
Labels: cla-signed

#208 Removes unnecessary usage of sudo form the package.
  package/opt/hassbian/suites/appdaemon.sh
  package/opt/hassbian/suites/duckdns.sh
  package/opt/hassbian/suites/hassbian-script.sh
  package/opt/hassbian/suites/hassbian.sh
  package/opt/hassbian/suites/hue.sh
  package/opt/hassbian/suites/libcec.sh
  package/opt/hassbian/suites/mosquitto.sh
  package/opt/hassbian/suites/samba.sh
  package/opt/hassbian/suites/webterminal.sh
  package/usr/local/bin/hassbian-config
Labels: Hacktoberfest, cla-signed, enhancement

#209 Merge Dev into master for release of 0.10.0
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .gitlab-ci.yml
  README.md
  docs/appdaemon.md
  docs/cloud9.md
  docs/duckdns.md
  docs/hassbian.md
  docs/hassbian_config.md
  docs/homeassistant.md
  docs/homebridge.md
  docs/hue.md
  docs/libcec.md
  docs/mariadb.md
  docs/monitor.md
  docs/mosquitto.md
  docs/mssql.md
  docs/pihole.md
  docs/postgresql.md
  docs/python.md
  docs/razberry.md
  docs/samba.md
  docs/tradfri.md
  docs/webterminal.md
  package/DEBIAN/control
  package/etc/apt/apt.d/01autoremove
  package/etc/bash_completion.d/hassbian-config
  package/etc/systemd/system/install_homeassistant.service
  package/etc/update-motd.d/10-display-hostname
  package/etc/update-motd.d/20-sysinfo
  package/etc/update-motd.d/30-services
  package/home/pi/.bash_aliases
  package/opt/hassbian/suites/appdaemon.sh
  package/opt/hassbian/suites/cloud9.sh
  package/opt/hassbian/suites/duckdns.sh
  package/opt/hassbian/suites/files/cloud9.service
  package/opt/hassbian/suites/files/dehydrated_cron
  package/opt/hassbian/suites/hassbian-script-dev.sh
  package/opt/hassbian/suites/hassbian-script.sh
  package/opt/hassbian/suites/hassbian.sh
  package/opt/hassbian/suites/homeassistant-dev.sh
  package/opt/hassbian/suites/homeassistant.sh
  package/opt/hassbian/suites/homebridge.sh
  package/opt/hassbian/suites/hue.sh
  package/opt/hassbian/suites/libcec.sh
  package/opt/hassbian/suites/monitor.sh
  package/opt/hassbian/suites/mosquitto.sh
  package/opt/hassbian/suites/pihole.sh
  package/opt/hassbian/suites/python.sh
  package/opt/hassbian/suites/razberry.sh
  package/opt/hassbian/suites/samba.sh
  package/opt/hassbian/suites/webterminal.sh
  package/usr/local/bin/hassbian-config
Labels: cla-signed, enhancement

#211 Add install script for fail2ban
  README.md
  docs/fail2ban.md
  package/opt/hassbian/suites/fail2ban.sh
Labels: New install script, cla-signed

#213 Change header from "Monitor" to "Pi-hole"
  docs/pihole.md
Labels: cla-signed

#214 Fix broken link to fail2ban-docs
  README.md
Labels: cla-signed
