Repository home-assistant/hassbian-scripts, pull requests merged in 2018-07, with the labels that each got.

#170 Initial preperations for hosting the package on GitLab
  .gitlab-ci.yml
  docs/hassbian_config.md
  package/opt/hassbian/suites/hassbian-script.sh
Labels: cla-signed

#172 Home Assistant: Rollback feature if the upgrade script fails config_check.
  package/opt/hassbian/suites/homeassistant.sh
Labels: cla-signed, enhancement

#174 Hassbian: make sure that crucial packages are not removed.
  package/etc/apt/apt.d/01autoremove
Labels: New functionality, cla-signed, enhancement
