Repository home-assistant/hassbian-scripts, pull requests merged in 2018-11, with the labels that each got.

#215 Release v0.11.0
  README.md
  docs/fail2ban.md
  docs/pihole.md
  docs/zigbee2mqtt.md
  package/DEBIAN/control
  package/opt/hassbian/suites/fail2ban.sh
  package/opt/hassbian/suites/zigbee2mqtt.sh
  package/usr/local/bin/hassbian-config
Labels: New functionality, cla-signed

#217 homeassistant: Move pip3 to python3 -m pip
  package/opt/hassbian/suites/homeassistant.sh
Labels: cla-signed

#220 Homeassistant: Set permissions before install.
  package/opt/hassbian/suites/homeassistant.sh
Labels: cla-signed, script: homeassistant

#222 Bump version 0.11.1
  package/DEBIAN/control
Labels: cla-signed

#223 Release 0.11.1
  package/DEBIAN/control
  package/opt/hassbian/suites/homeassistant.sh
Labels: cla-signed

#225 Fixed example
  docs/postgresql.md
Labels: cla-signed
