Repository home-assistant/hassbian-scripts, pull requests merged in 2018-02, with the labels that each got.

#99 Hassbian: Fixes install problem at Hassbian boot.
  package/etc/systemd/system/install_homeassistant.service
Labels: cla-signed

#100 Homeassistant: Moved versioncheck to PyPI.
  package/opt/hassbian/suites/homeassistant.sh
Labels: cla-signed

#101 Rename HASSbian to Hassbian.
  README.md
  docs/hassbian_config.md
  package/DEBIAN/control
Labels: cla-signed

#103 DuckDNS: Add support for typing the full domain.
  package/opt/hassbian/suites/duckdns.sh
Labels: cla-signed

#102 Initial addition of templates for issue/pr.
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#106 Fix wrong Discord channel in scripts
  package/opt/hassbian/suites/appdaemon.sh
  package/opt/hassbian/suites/hassbian.sh
  package/opt/hassbian/suites/tradfri.sh
Labels: cla-signed, enhancement

#107 Aliases for common functions.
  package/home/homeassistant/.bash_aliases
  package/home/pi/.bash_aliases
Labels: New functionality, cla-signed

#109 Moved user input to the top of the scripts.
  package/opt/hassbian/suites/appdaemon.sh
  package/opt/hassbian/suites/homebridge.sh
  package/opt/hassbian/suites/mosquitto.sh
Labels: cla-signed

#112 Preparations for Stickler CI
  package/.stickler.yml
  package/etc/bash_completion.d/hassbian-config
  package/opt/hassbian/suites/appdaemon.sh
  package/opt/hassbian/suites/duckdns.sh
  package/opt/hassbian/suites/hassbian-script-dev.sh
  package/opt/hassbian/suites/hassbian-script.sh
  package/opt/hassbian/suites/hassbian.sh
  package/opt/hassbian/suites/homeassistant-dev.sh
  package/opt/hassbian/suites/homeassistant.sh
  package/opt/hassbian/suites/homebridge.sh
  package/opt/hassbian/suites/hue.sh
  package/opt/hassbian/suites/libcec.sh
  package/opt/hassbian/suites/mariadb.sh
  package/opt/hassbian/suites/mosquitto.sh
  package/opt/hassbian/suites/mssql.sh
  package/opt/hassbian/suites/mysql.sh
  package/opt/hassbian/suites/postgresql.sh
  package/opt/hassbian/suites/razberry.sh
  package/opt/hassbian/suites/samba.sh
  package/opt/hassbian/suites/tradfri.sh
  package/opt/hassbian/suites/webterminal.sh
  package/usr/local/bin/hassbian-config
Labels: cla-signed

#114 Move stickler
  .stickler.yml
Labels: cla-signed

#113 Hassbian-config: Add log to upgrade function.
  package/usr/local/bin/hassbian-config
Labels: cla-signed

#115 AppDaemon: Updated documentation.
  docs/appdaemon.md
Labels: cla-signed

#116 PostgreSQL: Added client installation.
  package/opt/hassbian/suites/postgresql.sh
Labels: cla-signed

#119 Change shell from sh to bash
  .stickler.yml
Labels: cla-signed

#117 Improve text prompts
  package/opt/hassbian/suites/mariadb.sh
  package/opt/hassbian/suites/mssql.sh
  package/opt/hassbian/suites/mysql.sh
  package/opt/hassbian/suites/postgresql.sh
  package/opt/hassbian/suites/samba.sh
  package/opt/hassbian/suites/tradfri.sh
  package/opt/hassbian/suites/webterminal.sh
  package/usr/local/bin/hassbian-config
Labels: cla-signed

#121 Script validations.
  docs/homeassistant.md
  package/opt/hassbian/suites/appdaemon.sh
  package/opt/hassbian/suites/duckdns.sh
  package/opt/hassbian/suites/hassbian-script-dev.sh
  package/opt/hassbian/suites/hassbian-script.sh
  package/opt/hassbian/suites/hassbian.sh
  package/opt/hassbian/suites/homeassistant-dev.sh
  package/opt/hassbian/suites/homeassistant.sh
  package/opt/hassbian/suites/homebridge.sh
  package/opt/hassbian/suites/hue.sh
  package/opt/hassbian/suites/libcec.sh
  package/opt/hassbian/suites/mariadb.sh
  package/opt/hassbian/suites/mosquitto.sh
  package/opt/hassbian/suites/mssql.sh
  package/opt/hassbian/suites/mysql.sh
  package/opt/hassbian/suites/postgresql.sh
  package/opt/hassbian/suites/razberry.sh
  package/opt/hassbian/suites/samba.sh
  package/opt/hassbian/suites/tradfri.sh
  package/opt/hassbian/suites/webterminal.sh
Labels: cla-signed

#123 Fixed typo in validations
  package/opt/hassbian/suites/appdaemon.sh
  package/opt/hassbian/suites/homeassistant.sh
Labels: cla-signed

#125 hassbian-config: Usage cleanup, added new help and command options.
  docs/hassbian_config.md
  package/opt/hassbian/suites/libcec.sh
  package/opt/hassbian/suites/mariadb.sh
  package/opt/hassbian/suites/mosquitto.sh
  package/opt/hassbian/suites/mssql.sh
  package/opt/hassbian/suites/mysql.sh
  package/opt/hassbian/suites/postgresql.sh
  package/opt/hassbian/suites/samba.sh
  package/opt/hassbian/suites/tradfri.sh
  package/usr/local/bin/hassbian-config
Labels: cla-signed
