Repository home-assistant/hassbian-scripts, pull requests merged in 2019-05, with the labels that each got.

#270 Skip migration if osname is buster
  package/opt/hassbian/suites/homeassistant/install
Labels: cla-signed

#271 Change declarations
  package/opt/hassbian/helpers/workaround
  package/usr/local/bin/hassbian-config
Labels: cla-signed

#272 Changes to the test suite and minor bugfixes.
  package/opt/hassbian/helpers/developer
  package/opt/hassbian/helpers/info/general
  package/opt/hassbian/helpers/info/version
  package/opt/hassbian/helpers/log
  package/opt/hassbian/helpers/suite/action
  package/opt/hassbian/helpers/suite/verify
  package/opt/hassbian/suites/homeassistant/manifest
  package/opt/hassbian/suites/homeassistant/python-migration
  package/opt/hassbian/suites/hue/manifest
  package/opt/hassbian/suites/mosquitto/manifest
  package/opt/hassbian/suites/python/upgrade
Labels: cla-signed

#274 Add Check for repository file Remove purging of package since that ha…
  package/opt/hassbian/suites/hassbian-script/upgrade
Labels: Buster, cla-signed

#276 AppDaemon: Fixes "command not found" when running suite actions.
  package/opt/hassbian/suites/appdaemon/install
  package/opt/hassbian/suites/appdaemon/upgrade
Labels: cla-signed, suite: appdaemon

#277 Fix check of DUCKDNS token
  package/opt/hassbian/suites/duckdns/install
Labels: Buster, bug, cla-signed, suite: duckdns

#278 Fix color if new update
  package/opt/hassbian/helpers/info/general
Labels: cla-signed

#279 homeassistant: Fix for upgrade using beta/dev flags
  package/opt/hassbian/suites/homeassistant/upgrade
Labels: cla-signed

#280 python: Fix "migration" on a fresh install.
  package/opt/hassbian/suites/python/upgrade
Labels: cla-signed

#281 Tradfri: fix typo in function name.
  package/opt/hassbian/suites/tradfri/install
Labels: cla-signed

#282 input.text fix returned value
  package/opt/hassbian/helpers/input
Labels: cla-signed

#283 DuckDNS: Fixes issue with generating certificates and validation
  package/opt/hassbian/suites/duckdns/install
Labels: cla-signed

#284 Service file paths
  package/opt/hassbian/suites/custom-component-store/files/custom-component-store@homeassistant.service
  package/opt/hassbian/suites/manager/files/hassbian-manager@homeassistant.service
Labels: cla-signed

#285 Use debian version of mosquitto for buster
  package/opt/hassbian/suites/mosquitto/install
Labels: cla-signed

#287 Insert issue number for tracking
  package/opt/hassbian/suites/pihole/manifest
Labels: cla-signed

#289 Spelling correction premissions->permissions
  package/opt/hassbian/suites/homeassistant/install
  package/opt/hassbian/suites/homeassistant/upgrade
  package/opt/hassbian/suites/python/upgrade
Labels: cla-signed

#292 Python: use HA python version for validation, not HA
  package/opt/hassbian/suites/python/upgrade
Labels: bug, cla-signed, suite: python

#293 Dev into master
  package/opt/hassbian/suites/python/upgrade
Labels: cla-signed

#299 Docs: Corrected links and anchors
  docs/cli/cli.md
  docs/cli/helpers.md
  docs/cli/index.md
  docs/contribute/functions.md
  docs/contribute/index.md
  docs/contribute/suites.md
  docs/index.md
  docs/suites/appdaemon.md
  docs/suites/cloud9.md
  docs/suites/custom-component-store.md
  docs/suites/duckdns.md
  docs/suites/fail2ban.md
  docs/suites/hassbian.md
  docs/suites/hassbian_config.md
  docs/suites/homeassistant.md
  docs/suites/hue.md
  docs/suites/index.md
  docs/suites/libcec.md
  docs/suites/manager.md
  docs/suites/mariadb.md
  docs/suites/monitor.md
  docs/suites/mosquitto.md
  docs/suites/mssql.md
  docs/suites/pihole.md
  docs/suites/postgresql.md
  docs/suites/python.md
  docs/suites/razberry.md
  docs/suites/samba.md
  docs/suites/template.md
  docs/suites/tradfri.md
  docs/suites/webterminal.md
  docs/suites/zigbee2mqtt.md
Labels: cla-signed
